version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongo:27017/uav_analysis
    depends_on:
      - mongo
    volumes:
      - ./UAV_Analysis_Platform/uploads:/app/UAV_Analysis_Platform/uploads

  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: